[package]
name = "aoc-2020"
version = "0.1.0"
authors = ["riari"]
edition = "2018"

[lib]
name = "util"
path = "src/util.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
